# Generated by Django 3.2.24 on 2024-02-22 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0015_auto_20230806_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coop',
            name='phone',
        ),
        migrations.AddField(
            model_name='coop',
            name='contact_methods',
            field=models.ManyToManyField(to='directory.ContactMethod'),
        ),
        migrations.AlterField(
            model_name='coop',
            name='rec_updated_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
