# Generated by Django 3.2.24 on 2024-02-22 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0016_auto_20240222_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='rec_updated_by',
        ),
        migrations.AddField(
            model_name='coop',
            name='rec_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coops', to=settings.AUTH_USER_MODEL),
        ),
    ]
