# Generated by Django 3.2.24 on 2024-02-24 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0017_auto_20240222_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coop',
            name='rec_updated_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contactmethod',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='contactmethod',
            name='coops',
        ),
        migrations.RemoveField(
            model_name='contactmethod',
            name='email_is_public',
        ),
        migrations.RemoveField(
            model_name='contactmethod',
            name='phone_is_public',
        ),
    ]
