# Generated by Django 3.2.24 on 2024-02-25 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_alter_coop_rec_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coopaddresstags',
            name='coop',
        ),
        migrations.RemoveField(
            model_name='coop',
            name='addresses',
        ),
        migrations.AddField(
            model_name='coop',
            name='addresses',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.coopaddresstags'),
        ),
    ]
