# Generated by Django 3.2.24 on 2024-02-25 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20240225_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coop',
            name='addresses',
        ),
        migrations.AddField(
            model_name='coopaddresstags',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='directory.coop'),
        ),
    ]
