# Generated by Django 3.2.24 on 2024-03-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0023_auto_20240307_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=320)),
                ('response', models.JSONField()),
                ('place_id', models.CharField(max_length=50)),
            ],
        ),
    ]
