# Generated by Django 3.2.24 on 2024-03-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0024_addresscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=165, null=True),
        ),
    ]
