# Generated by Django 3.2.24 on 2024-03-20 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0025_address_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopPublic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('web_site', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('scope', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('request_datetime', models.DateTimeField()),
                ('review_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'directory_coop_public',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoopProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('web_site', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('scope', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
                ('request_datetime', models.DateTimeField()),
                ('review_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=8)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=6)),
                ('change_summary', models.JSONField(verbose_name='Change Summary')),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('coop_public', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.cooppublic')),
            ],
            options={
                'db_table': 'directory_coop_proposal',
                'abstract': False,
            },
        ),
    ]
