# Generated by Django 3.2.24 on 2024-03-21 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('directory', '0026_coopproposal_cooppublic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coopproposal',
            old_name='request_datetime',
            new_name='requested_datetime',
        ),
        migrations.RenameField(
            model_name='coopproposal',
            old_name='review_datetime',
            new_name='reviewed_datetime',
        ),
        migrations.RenameField(
            model_name='cooppublic',
            old_name='review_datetime',
            new_name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='request_datetime',
        ),
        migrations.AddField(
            model_name='coopproposal',
            name='proposal_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coopproposal',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coopproposal',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooppublic',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooppublic',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='last_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cooppublic',
            name='last_modified_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='cooppublic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterField(
            model_name='coopproposal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HIDDEN', 'Hidden'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=8),
        ),
    ]
