# Generated by Django 3.2.24 on 2024-03-21 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0027_auto_20240321_0703'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoopX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('web_site', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('scope', models.TextField(null=True)),
                ('tags', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='name',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='status',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='coopproposal',
            name='web_site',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='cooppublic',
            name='web_site',
        ),
        migrations.AlterField(
            model_name='cooppublic',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('REMOVED', 'Removed')], default='ACTIVE', max_length=8),
        ),
        migrations.AlterModelTable(
            name='coopproposal',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cooppublic',
            table=None,
        ),
        migrations.AddField(
            model_name='coopproposal',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.coopx'),
        ),
        migrations.AddField(
            model_name='cooppublic',
            name='coop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='directory.coopx'),
        ),
    ]
