# Generated by Django 3.2.24 on 2024-03-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0028_auto_20240321_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopx',
            name='contact_methods',
            field=models.ManyToManyField(to='directory.ContactMethod'),
        ),
        migrations.AddField(
            model_name='coopx',
            name='types',
            field=models.ManyToManyField(to='directory.CoopType'),
        ),
        migrations.CreateModel(
            name='PersonX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('is_public', models.BooleanField(default=True)),
                ('contact_methods', models.ManyToManyField(to='directory.ContactMethod')),
            ],
        ),
        migrations.CreateModel(
            name='CoopAddressTagsX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.address')),
            ],
        ),
        migrations.AddField(
            model_name='coopx',
            name='addresses',
            field=models.ManyToManyField(to='directory.CoopAddressTagsX'),
        ),
        migrations.AddField(
            model_name='coopx',
            name='people',
            field=models.ManyToManyField(to='directory.PersonX'),
        ),
    ]
