# Generated by Django 3.2.24 on 2024-03-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0032_auto_20240325_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoopX',
            new_name='Coop',
        ),
        migrations.RenameModel(
            old_name='CoopAddressTagsX',
            new_name='CoopAddressTags',
        ),
        migrations.RenameModel(
            old_name='PersonX',
            new_name='Person',
        ),
    ]
