# Generated by Django 3.2.24 on 2024-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0033_auto_20240325_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooptype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
