# Generated by Django 3.2.24 on 2024-04-09 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0034_alter_cooptype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cooptype',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
